plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма C4: Система управления отоплением

Person(installer, "Монтажник", "Профессиональная установка и подключение оборудования")
Person(user, "Пользователь", "Включает/выключает отопление")

System(heating_system, "Система управления отоплением", "Монолитное приложение на Go: управление отоплением и мониторинг температуры")

System_Ext(sensor, "Датчик температуры", "Измеряет текущую температуру")
System_Ext(heater, "Отопительное оборудование", "Обогреватели, котлы и другие устройства")

Rel(installer, heating_system, "Регистрирует новое оборудование\nв системе")
Rel(installer, sensor, "Физический монтаж и\nподключение датчиков")
Rel(installer, heater, "Физический монтаж и\nподключение отопительного оборудования")
Rel(user, heating_system, "Управляет отоплением\nУстанавливает температуру\nПросматривает показания датчиков")

Rel(heating_system, sensor, "Опрашивает температуру\n(синхронный запрос)")
Rel(heating_system, heater, "Управляет включением/выключением\n(синхронная команда)")

@enduml