
# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# WebFlux
springdoc.swagger-ui.use-root-path=false


# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST:/}
logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG